/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

/**
 *
 * @author Usuario
 */
public class MenuPrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalForm
     */
    public MenuPrincipalForm() {
        initComponents();
        this.mostrarBotonesMenu();
    }
    
    private void irRegistrarResiduo(){
        new RegistrarResiduoForm().setVisible(true);
        this.dispose();
    }
    
    private void irSolicitarTraslado(){
        new SolicitarTrasladoForm().setVisible(true);
        this.dispose();
    }
    
    private void irAsignarTraslados(){
        new AsignarTrasladosForm().setVisible(true);
        this.dispose();
    }
    
    private void irRegistrarTraslado(){
        new TrasladosAsignadosForm().setVisible(true);
        this.dispose();
    }
    
    private void mostrarBotonesMenu(){
        if (comboActores.getSelectedItem() == "Selecciona" ) {
            btnAsignarTraslado.setVisible(false);
            btnRegistrarResiduo.setVisible(false);
            btnRegistrarTraslado.setVisible(false);
            btnSolicitarTraslado.setVisible(false);
        } else if (comboActores.getSelectedItem() == "Productor") {
            btnAsignarTraslado.setVisible(false);
            btnRegistrarResiduo.setVisible(true);
            btnRegistrarTraslado.setVisible(false);
            btnSolicitarTraslado.setVisible(true);
        } else if (comboActores.getSelectedItem() == "Empresa Transportista") {
            btnAsignarTraslado.setVisible(false);
            btnRegistrarResiduo.setVisible(false);
            btnRegistrarTraslado.setVisible(true);
            btnSolicitarTraslado.setVisible(false);
        } else {
            btnAsignarTraslado.setVisible(true);
            btnRegistrarResiduo.setVisible(false);
            btnRegistrarTraslado.setVisible(false);
            btnSolicitarTraslado.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarResiduo = new javax.swing.JButton();
        btnSolicitarTraslado = new javax.swing.JButton();
        btnRegistrarTraslado = new javax.swing.JButton();
        btnAsignarTraslado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboActores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        btnRegistrarResiduo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegistrarResiduo.setText("Registrar Residuo");
        btnRegistrarResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarResiduoActionPerformed(evt);
            }
        });

        btnSolicitarTraslado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSolicitarTraslado.setText("Solicitar Traslado de Residuos");
        btnSolicitarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarTrasladoActionPerformed(evt);
            }
        });

        btnRegistrarTraslado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegistrarTraslado.setText("Registrar Traslado");
        btnRegistrarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTrasladoActionPerformed(evt);
            }
        });

        btnAsignarTraslado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAsignarTraslado.setText("Asignar Traslados a Empresas");
        btnAsignarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTrasladoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Actuar Como:");

        comboActores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Productor", "Empresa Transportista", "Administrador" }));
        comboActores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarTraslado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSolicitarTraslado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarResiduo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAsignarTraslado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(comboActores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboActores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnRegistrarResiduo)
                .addGap(46, 46, 46)
                .addComponent(btnSolicitarTraslado)
                .addGap(39, 39, 39)
                .addComponent(btnRegistrarTraslado)
                .addGap(37, 37, 37)
                .addComponent(btnAsignarTraslado)
                .addGap(57, 57, 57))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarResiduoActionPerformed
        // TODO add your handling code here:
        this.irRegistrarResiduo();
    }//GEN-LAST:event_btnRegistrarResiduoActionPerformed

    private void btnSolicitarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarTrasladoActionPerformed
        // TODO add your handling code here:
        this.irSolicitarTraslado();
    }//GEN-LAST:event_btnSolicitarTrasladoActionPerformed

    private void btnAsignarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTrasladoActionPerformed
        // TODO add your handling code here:
        this.irAsignarTraslados();
    }//GEN-LAST:event_btnAsignarTrasladoActionPerformed

    private void btnRegistrarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTrasladoActionPerformed
        // TODO add your handling code here:
        this.irRegistrarTraslado();
    }//GEN-LAST:event_btnRegistrarTrasladoActionPerformed

    private void comboActoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActoresActionPerformed
        // TODO add your handling code here:
        this.mostrarBotonesMenu();
    }//GEN-LAST:event_comboActoresActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarTraslado;
    private javax.swing.JButton btnRegistrarResiduo;
    private javax.swing.JButton btnRegistrarTraslado;
    private javax.swing.JButton btnSolicitarTraslado;
    private javax.swing.JComboBox<String> comboActores;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
